/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AdService } from "../ad.service";
import { AdCreateInput } from "./AdCreateInput";
import { Ad } from "./Ad";
import { AdFindManyArgs } from "./AdFindManyArgs";
import { AdWhereUniqueInput } from "./AdWhereUniqueInput";
import { AdUpdateInput } from "./AdUpdateInput";

export class AdControllerBase {
  constructor(protected readonly service: AdService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Ad })
  async createAd(@common.Body() data: AdCreateInput): Promise<Ad> {
    return await this.service.createAd({
      data: data,
      select: {
        Name: true,
        createdAt: true,
        description: true,
        id: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Ad] })
  @ApiNestedQuery(AdFindManyArgs)
  async ads(@common.Req() request: Request): Promise<Ad[]> {
    const args = plainToClass(AdFindManyArgs, request.query);
    return this.service.ads({
      ...args,
      select: {
        Name: true,
        createdAt: true,
        description: true,
        id: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Ad })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async ad(@common.Param() params: AdWhereUniqueInput): Promise<Ad | null> {
    const result = await this.service.ad({
      where: params,
      select: {
        Name: true,
        createdAt: true,
        description: true,
        id: true,
        price: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Ad })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAd(
    @common.Param() params: AdWhereUniqueInput,
    @common.Body() data: AdUpdateInput
  ): Promise<Ad | null> {
    try {
      return await this.service.updateAd({
        where: params,
        data: data,
        select: {
          Name: true,
          createdAt: true,
          description: true,
          id: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Ad })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAd(
    @common.Param() params: AdWhereUniqueInput
  ): Promise<Ad | null> {
    try {
      return await this.service.deleteAd({
        where: params,
        select: {
          Name: true,
          createdAt: true,
          description: true,
          id: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Post("/:id/latest")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async Latest(
    @common.Body()
    body: AdCreateInput
  ): Promise<string> {
    return this.service.Latest(body);
  }
}
