/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CategoryItemService } from "../categoryItem.service";
import { CategoryItemCreateInput } from "./CategoryItemCreateInput";
import { CategoryItem } from "./CategoryItem";
import { CategoryItemFindManyArgs } from "./CategoryItemFindManyArgs";
import { CategoryItemWhereUniqueInput } from "./CategoryItemWhereUniqueInput";
import { CategoryItemUpdateInput } from "./CategoryItemUpdateInput";

export class CategoryItemControllerBase {
  constructor(protected readonly service: CategoryItemService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CategoryItem })
  async createCategoryItem(
    @common.Body() data: CategoryItemCreateInput
  ): Promise<CategoryItem> {
    return await this.service.createCategoryItem({
      data: {
        ...data,

        category: data.category
          ? {
              connect: data.category,
            }
          : undefined,
      },
      select: {
        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        max: true,
        min: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [CategoryItem] })
  @ApiNestedQuery(CategoryItemFindManyArgs)
  async categoryItems(@common.Req() request: Request): Promise<CategoryItem[]> {
    const args = plainToClass(CategoryItemFindManyArgs, request.query);
    return this.service.categoryItems({
      ...args,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        max: true,
        min: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CategoryItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async categoryItem(
    @common.Param() params: CategoryItemWhereUniqueInput
  ): Promise<CategoryItem | null> {
    const result = await this.service.categoryItem({
      where: params,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        max: true,
        min: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CategoryItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCategoryItem(
    @common.Param() params: CategoryItemWhereUniqueInput,
    @common.Body() data: CategoryItemUpdateInput
  ): Promise<CategoryItem | null> {
    try {
      return await this.service.updateCategoryItem({
        where: params,
        data: {
          ...data,

          category: data.category
            ? {
                connect: data.category,
              }
            : undefined,
        },
        select: {
          category: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          max: true,
          min: true,
          name: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CategoryItem })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCategoryItem(
    @common.Param() params: CategoryItemWhereUniqueInput
  ): Promise<CategoryItem | null> {
    try {
      return await this.service.deleteCategoryItem({
        where: params,
        select: {
          category: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          max: true,
          min: true,
          name: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
