/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  CategoryItem as PrismaCategoryItem,
  Category as PrismaCategory,
} from "@prisma/client";

export class CategoryItemServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CategoryItemCountArgs, "select">
  ): Promise<number> {
    return this.prisma.categoryItem.count(args);
  }

  async categoryItems(
    args: Prisma.CategoryItemFindManyArgs
  ): Promise<PrismaCategoryItem[]> {
    return this.prisma.categoryItem.findMany(args);
  }
  async categoryItem(
    args: Prisma.CategoryItemFindUniqueArgs
  ): Promise<PrismaCategoryItem | null> {
    return this.prisma.categoryItem.findUnique(args);
  }
  async createCategoryItem(
    args: Prisma.CategoryItemCreateArgs
  ): Promise<PrismaCategoryItem> {
    return this.prisma.categoryItem.create(args);
  }
  async updateCategoryItem(
    args: Prisma.CategoryItemUpdateArgs
  ): Promise<PrismaCategoryItem> {
    return this.prisma.categoryItem.update(args);
  }
  async deleteCategoryItem(
    args: Prisma.CategoryItemDeleteArgs
  ): Promise<PrismaCategoryItem> {
    return this.prisma.categoryItem.delete(args);
  }

  async getCategory(parentId: string): Promise<PrismaCategory | null> {
    return this.prisma.categoryItem
      .findUnique({
        where: { id: parentId },
      })
      .category();
  }
}
