/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CategoryItem } from "./CategoryItem";
import { CategoryItemCountArgs } from "./CategoryItemCountArgs";
import { CategoryItemFindManyArgs } from "./CategoryItemFindManyArgs";
import { CategoryItemFindUniqueArgs } from "./CategoryItemFindUniqueArgs";
import { CreateCategoryItemArgs } from "./CreateCategoryItemArgs";
import { UpdateCategoryItemArgs } from "./UpdateCategoryItemArgs";
import { DeleteCategoryItemArgs } from "./DeleteCategoryItemArgs";
import { Category } from "../../category/base/Category";
import { CategoryItemService } from "../categoryItem.service";
@graphql.Resolver(() => CategoryItem)
export class CategoryItemResolverBase {
  constructor(protected readonly service: CategoryItemService) {}

  async _categoryItemsMeta(
    @graphql.Args() args: CategoryItemCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CategoryItem])
  async categoryItems(
    @graphql.Args() args: CategoryItemFindManyArgs
  ): Promise<CategoryItem[]> {
    return this.service.categoryItems(args);
  }

  @graphql.Query(() => CategoryItem, { nullable: true })
  async categoryItem(
    @graphql.Args() args: CategoryItemFindUniqueArgs
  ): Promise<CategoryItem | null> {
    const result = await this.service.categoryItem(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CategoryItem)
  async createCategoryItem(
    @graphql.Args() args: CreateCategoryItemArgs
  ): Promise<CategoryItem> {
    return await this.service.createCategoryItem({
      ...args,
      data: {
        ...args.data,

        category: args.data.category
          ? {
              connect: args.data.category,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => CategoryItem)
  async updateCategoryItem(
    @graphql.Args() args: UpdateCategoryItemArgs
  ): Promise<CategoryItem | null> {
    try {
      return await this.service.updateCategoryItem({
        ...args,
        data: {
          ...args.data,

          category: args.data.category
            ? {
                connect: args.data.category,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CategoryItem)
  async deleteCategoryItem(
    @graphql.Args() args: DeleteCategoryItemArgs
  ): Promise<CategoryItem | null> {
    try {
      return await this.service.deleteCategoryItem(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Category, {
    nullable: true,
    name: "category",
  })
  async getCategory(
    @graphql.Parent() parent: CategoryItem
  ): Promise<Category | null> {
    const result = await this.service.getCategory(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
