/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CategoryService } from "../category.service";
import { CategoryCreateInput } from "./CategoryCreateInput";
import { Category } from "./Category";
import { CategoryFindManyArgs } from "./CategoryFindManyArgs";
import { CategoryWhereUniqueInput } from "./CategoryWhereUniqueInput";
import { CategoryUpdateInput } from "./CategoryUpdateInput";
import { CategoryItemFindManyArgs } from "../../categoryItem/base/CategoryItemFindManyArgs";
import { CategoryItem } from "../../categoryItem/base/CategoryItem";
import { CategoryItemWhereUniqueInput } from "../../categoryItem/base/CategoryItemWhereUniqueInput";

export class CategoryControllerBase {
  constructor(protected readonly service: CategoryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Category })
  async createCategory(
    @common.Body() data: CategoryCreateInput
  ): Promise<Category> {
    return await this.service.createCategory({
      data: {
        ...data,

        cat_Id: data.cat_Id
          ? {
              connect: data.cat_Id,
            }
          : undefined,

        parentId: data.parentId
          ? {
              connect: data.parentId,
            }
          : undefined,
      },
      select: {
        cat_Id: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,

        parentId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Category] })
  @ApiNestedQuery(CategoryFindManyArgs)
  async categories(@common.Req() request: Request): Promise<Category[]> {
    const args = plainToClass(CategoryFindManyArgs, request.query);
    return this.service.categories({
      ...args,
      select: {
        cat_Id: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,

        parentId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Category })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async category(
    @common.Param() params: CategoryWhereUniqueInput
  ): Promise<Category | null> {
    const result = await this.service.category({
      where: params,
      select: {
        cat_Id: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,

        parentId: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Category })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCategory(
    @common.Param() params: CategoryWhereUniqueInput,
    @common.Body() data: CategoryUpdateInput
  ): Promise<Category | null> {
    try {
      return await this.service.updateCategory({
        where: params,
        data: {
          ...data,

          cat_Id: data.cat_Id
            ? {
                connect: data.cat_Id,
              }
            : undefined,

          parentId: data.parentId
            ? {
                connect: data.parentId,
              }
            : undefined,
        },
        select: {
          cat_Id: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,

          parentId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Category })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCategory(
    @common.Param() params: CategoryWhereUniqueInput
  ): Promise<Category | null> {
    try {
      return await this.service.deleteCategory({
        where: params,
        select: {
          cat_Id: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,

          parentId: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/categoryItems")
  @ApiNestedQuery(CategoryItemFindManyArgs)
  async findCategoryItems(
    @common.Req() request: Request,
    @common.Param() params: CategoryWhereUniqueInput
  ): Promise<CategoryItem[]> {
    const query = plainToClass(CategoryItemFindManyArgs, request.query);
    const results = await this.service.findCategoryItems(params.id, {
      ...query,
      select: {
        category: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        max: true,
        min: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/categoryItems")
  async connectCategoryItems(
    @common.Param() params: CategoryWhereUniqueInput,
    @common.Body() body: CategoryItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoryItems: {
        connect: body,
      },
    };
    await this.service.updateCategory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/categoryItems")
  async updateCategoryItems(
    @common.Param() params: CategoryWhereUniqueInput,
    @common.Body() body: CategoryItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoryItems: {
        set: body,
      },
    };
    await this.service.updateCategory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/categoryItems")
  async disconnectCategoryItems(
    @common.Param() params: CategoryWhereUniqueInput,
    @common.Body() body: CategoryItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      categoryItems: {
        disconnect: body,
      },
    };
    await this.service.updateCategory({
      where: params,
      data,
      select: { id: true },
    });
  }
}
